spring:
  application:
    name: api-gateway
  profiles:
    default: eureka-on
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
